# Generated by Django 3.2.5 on 2021-07-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='findished',
        ),
        migrations.AddField(
            model_name='todos',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
